version: '3.7'

services:
  dms:
    image: mvbachman/dms:latest
    build:
      context: .
      dockerfile: dms.Dockerfile
    container_name: dms
    restart: always

    # Usually a good idea to not use 8000, other services may want it.
    ports:
      - 8001:8001

    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=dms
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=dms-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
volumes:
  postgres_data: