# Generated by Django 3.1.4 on 2020-12-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20201221_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_new_time_off',
            field=models.BooleanField(default=True, help_text='Receive an email when time off is requested and the status is pending', verbose_name='New Time Off'),
        ),
    ]
