# Generated by Django 3.1.4 on 2020-12-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_email_new_time_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_new_employee',
            field=models.BooleanField(default=True, help_text='Receive an email when a new employee is added', verbose_name='New Employee'),
        ),
    ]
