# Generated by Django 3.1.4 on 2021-01-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210104_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='termination_type',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Voluntary'), ('1', 'Involuntary')], max_length=30, null=True, verbose_name='Termination Type'),
        ),
    ]
