# Generated by Django 3.1.4 on 2021-01-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210104_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='display_name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
