# Generated by Django 3.1.4 on 2021-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20210105_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
