# Generated by Django 3.1.4 on 2021-01-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_attendance_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetypoint',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
