# Generated by Django 3.1.4 on 2021-01-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_safetypoint_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='edited_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
