# Generated by Django 3.1.4 on 2021-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20210106_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_safety_doc_day10',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 10 or more days sincea safety point was given but a signed documenthas not been uploaded', verbose_name='10 Days Past Due Safety Point'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_safety_doc_day3',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 or more days sincea safety point was given but a signed documenthas not been uploaded', verbose_name='3 Days Past Due Safety Point'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_safety_doc_day5',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 5 or more days sincea safety point was given but a signed documenthas not been uploaded', verbose_name='5 Days Past Due Safety Point'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_safety_doc_day7',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 7 or more days sincea safety point was given but a signed documenthas not been uploaded', verbose_name='7 Days Past Due Safety Point'),
        ),
    ]
