# Generated by Django 3.1.4 on 2021-01-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20210107_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_counseling_doc_day10',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 10 or more days sincea counseling was given but a signed documenthas not been uploaded', verbose_name='10 Days Past Due Counseling'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_counseling_doc_day3',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 or more days sincea counseling was given but a signed documenthas not been uploaded', verbose_name='3 Days Past Due Counseling'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_counseling_doc_day5',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 5 or more days sincea counseling was given but a signed documenthas not been uploaded', verbose_name='5 Days Past Due Counseling'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_counseling_doc_day7',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 7 or more days sincea counseling was given but a signed documenthas not been uploaded', verbose_name='7 Days Past Due Counseling'),
        ),
    ]
