# Generated by Django 3.1.4 on 2021-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20210107_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email_settlement_doc_day10',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email_settlement_doc_day3',
        ),
        migrations.AddField(
            model_name='employee',
            name='email_settlement_doc',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 or more days sincea settlement was created but a signed documenthas not been uploaded', verbose_name='Past Due Settlement'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_attendance_doc_day3',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 days sincean attendance point was given but a signed documenthas not been uploaded', verbose_name='3 Days Past Due Attendance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_attendance_doc_day5',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 5 days sincean attendance point was given but a signed documenthas not been uploaded', verbose_name='5 Days Past Due Attendance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_attendance_doc_day7',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 7 days sincean attendance point was given but a signed documenthas not been uploaded', verbose_name='7 Days Past Due Attendance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_counseling_doc_day3',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 days sincea counseling was given but a signed documenthas not been uploaded', verbose_name='3 Days Past Due Counseling'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_counseling_doc_day5',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 5 days sincea counseling was given but a signed documenthas not been uploaded', verbose_name='5 Days Past Due Counseling'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_counseling_doc_day7',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 7 days sincea counseling was given but a signed documenthas not been uploaded', verbose_name='7 Days Past Due Counseling'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_safety_doc_day3',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 days sincea safety point was given but a signed documenthas not been uploaded', verbose_name='3 Days Past Due Safety Point'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_safety_doc_day5',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 5 days sincea safety point was given but a signed documenthas not been uploaded', verbose_name='5 Days Past Due Safety Point'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_safety_doc_day7',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 7 days sincea safety point was given but a signed documenthas not been uploaded', verbose_name='7 Days Past Due Safety Point'),
        ),
    ]
