# Generated by Django 3.1.4 on 2021-01-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_auto_20210107_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='floating_holiday',
            field=models.IntegerField(default=0, verbose_name='Floating Holiday'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='paid_sick',
            field=models.IntegerField(default=0, verbose_name='Paid Sick'),
        ),
    ]
