# Generated by Django 3.1.4 on 2021-02-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_auto_20210202_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling',
            name='override_by',
            field=models.IntegerField(null=True),
        ),
    ]
