# Generated by Django 3.1.4 on 2021-02-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_counseling_override_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_attendance_doc_day10',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 10 or more days since an attendance point was given but a signed document has not been uploaded', verbose_name='10 Days Past Due Attendance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_attendance_doc_day3',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 days since an attendance point was given but a signed document has not been uploaded', verbose_name='3 Days Past Due Attendance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_attendance_doc_day5',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 5 days since an attendance point was given but a signed document has not been uploaded', verbose_name='5 Days Past Due Attendance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_attendance_doc_day7',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 7 days since an attendance point was given but a signed document has not been uploaded', verbose_name='7 Days Past Due Attendance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_counseling_doc_day10',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 10 or more days since a counseling was given but a signed document has not been uploaded', verbose_name='10 Days Past Due Counseling'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_counseling_doc_day3',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 days since a counseling was given but a signed document has not been uploaded', verbose_name='3 Days Past Due Counseling'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_counseling_doc_day5',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 5 days since a counseling was given but a signed document has not been uploaded', verbose_name='5 Days Past Due Counseling'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_counseling_doc_day7',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 7 days since a counseling was given but a signed document has not been uploaded', verbose_name='7 Days Past Due Counseling'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_safety_doc_day10',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 10 or more days since a safety point was given but a signed document has not been uploaded', verbose_name='10 Days Past Due Safety Point'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_safety_doc_day3',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 days since a safety point was given but a signed document has not been uploaded', verbose_name='3 Days Past Due Safety Point'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_safety_doc_day5',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 5 days since a safety point was given but a signed document has not been uploaded', verbose_name='5 Days Past Due Safety Point'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_safety_doc_day7',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 7 days since a safety point was given but a signed document has not been uploaded', verbose_name='7 Days Past Due Safety Point'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email_settlement_doc',
            field=models.BooleanField(default=True, help_text='Receive an email when it has been 3 or more days since a settlement was created but a signed document has not been uploaded', verbose_name='Past Due Settlement'),
        ),
    ]
