# Generated by Django 3.1.4 on 2021-02-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_auto_20210205_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='counseling',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='safetypoint',
            name='downloaded',
        ),
    ]
