# Generated by Django 3.1.4 on 2021-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_auto_20210205_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('', ''), ('driver', 'Driver'), ('mechanic', 'Mechanic'), ('utility', 'Utility'), ('dispatcher', 'Dispatcher'), ('dispatch_supervisor', 'Dispatch Supervisor'), ('driver_scheduler', 'Driver Scheduler'), ('hiring_supervisor', 'Hiring Supervisor'), ('clerk', 'Clerk'), ('agm', 'AGM'), ('gm', 'GM'), ('it_manager', 'IT Manager')], max_length=30, verbose_name='Position'),
        ),
    ]
