# Generated by Django 3.1.6 on 2021-02-15 16:54

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_auto_20210208_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='exemption',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'FMLA'), ('1', 'Paid Sick'), ('2', 'Unpaid Sick'), ('3', 'Union Agreement'), ('4', 'Excused Absence'), ('4', 'Attendance Incentives')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
