# Generated by Django 3.1.6 on 2021-04-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_auto_20210216_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='exemption',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'FMLA'), ('1', 'Paid Sick'), ('2', 'Unpaid Sick'), ('3', 'Union Agreement'), ('4', 'Excused Absence'), ('5', 'Attendance Incentive')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('', ''), ('driver', 'Driver'), ('mechanic', 'Mechanic'), ('utility', 'Utility'), ('dispatcher', 'Dispatcher'), ('dispatch_supervisor', 'Dispatch Supervisor'), ('driver_scheduler', 'Driver Scheduler'), ('hiring_supervisor', 'Hiring Supervisor'), ('road_supervisor', 'Road Supervisor'), ('operations_supervisor', 'Operations Supervisor'), ('clerk', 'Clerk'), ('agm', 'AGM'), ('gm', 'GM'), ('drive_cam_manager', 'Drive Cam Manager'), ('it_manager', 'IT Manager')], max_length=30, verbose_name='Position'),
        ),
    ]
