# Generated by Django 3.1.6 on 2021-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_auto_20210410_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('', ''), ('driver', 'Driver'), ('mechanic', 'Mechanic'), ('utility', 'Utility'), ('dispatcher', 'Dispatcher'), ('dispatch_supervisor', 'Dispatch Supervisor'), ('driver_scheduler', 'Driver Scheduler'), ('hiring_supervisor', 'Hiring Supervisor'), ('road_supervisor', 'Road Supervisor'), ('operations_supervisor', 'Operations Supervisor'), ('clerk', 'Clerk'), ('agm', 'AGM'), ('gm', 'GM'), ('drive_cam_manager', 'Drive Cam Manager'), ('safety_manager', 'Safety Manager'), ('it_manager', 'IT Manager')], max_length=30, verbose_name='Position'),
        ),
    ]
