# Generated by Django 3.1.6 on 2021-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_auto_20210413_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hold',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hold',
            name='training_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
