# Generated by Django 3.1.4 on 2021-05-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_auto_20210426_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_pending_term',
        ),
    ]
