# Generated by Django 3.1.6 on 2021-05-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_remove_employee_is_pending_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_all_accounts', 'Can view all accounts'), ('can_edit_employee_info', 'Can edit employee information'), ('can_assign_attendance', 'Can assign attendance records'), ('can_delete_attendance', 'Can delete attendance records'), ('can_edit_attendance', 'Can edit attendance records'), ('can_download_attendance', 'Can download attendance records'), ('can_assign_counseling', 'Can assign counseling'), ('can_delete_counseling', 'Can delete counseling'), ('can_edit_counseling', 'Can edit counseling'), ('can_download_counseling', 'Can download counseling'), ('can_assign_safety_point', 'Can assign safety point'), ('can_delete_safety_point', 'Can delete safety point'), ('can_edit_safety_point', 'Can edit safety point'), ('can_download_safety_point', 'Can download safety point'), ('can_place_hold', 'Can place hold'), ('can_remove_hold', 'Can remove hold'), ('can_remove_employee', 'Can remove employee'), ('can_terminate_employee', 'Can remove employee'), ('can_export_profile', 'Can export profile'), ('can_export_attendance_history', 'Can export attendance history'), ('can_export_safety_history', 'Can export safety history'), ('can_export_counseling_history', 'Can export counseling history'), ('can_view_settlement', 'Can view settlement'), ('can_create_settlement', 'Can create settlement'), ('can_upload_profile_picture', 'Can upload profile picture'), ('can_view_all_details', 'Can view details in account'), ('can_view_attendance_details', 'Can view attendance details in account'), ('can_view_safety_details', 'Can view safety details in account'), ('can_view_counseling_details', 'Can view counseling details in account'), ('can_override_progressive_discipline_lock', 'Can override progressive discipline lock'), ('can_view_employee_info', 'Can view employee info'), ('can_export_safety_meeting_attendance', 'Can export safety meeting attendance list'), ('can_export_phone_list', 'Can export phone list'), ('can_export_seniority_list', 'Can export seniority list'), ('can_export_driver_list', 'Can export driver list'), ('can_export_main_custom_list', 'Can export main custom list'), ('can_view_import_data', 'Can view import data'), ('can_import_driver_data', 'Can import driver data'), ('can_import_attendance_data', 'Can import attendance data'), ('can_import_safety_point_data', 'Can import safety point data'), ('can_view_operations_home', 'Can view operations home'), ('can_add_employee', 'Can add employee'), ('can_view_hold_list', 'Can view hold list'), ('can_view_attendance_reports', 'Can view attendance reports'), ('can_view_counseling_reports', 'Can view counseling reports'), ('can_add_time_off_request', 'Can add time off request'), ('can_delete_time_off_request', 'Can delete time off request'), ('can_view_time_off_reports', 'Can view time off reports'), ('can_view_termination_reports', 'Can view termination reports')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
