# Generated by Django 3.1.4 on 2021-05-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_auto_20210507_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='uploaded',
            new_name='signed',
        ),
        migrations.AddField(
            model_name='attendance',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
