# Generated by Django 3.1.6 on 2021-05-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_auto_20210510_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='signature_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
