# Generated by Django 3.1.6 on 2021-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_attendance_signature_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='signed',
            new_name='is_signed',
        ),
        migrations.AddField(
            model_name='attendance',
            name='singed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='exemption',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'FMLA'), ('1', 'Paid Sick'), ('2', 'Unpaid Sick'), ('3', 'Union Agreement'), ('4', 'Excused Absence'), ('5', 'Attendance Incentive')], default='', max_length=30),
        ),
    ]
