# Generated by Django 3.1.6 on 2021-05-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_auto_20210517_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='singed_date',
            new_name='signed_date',
        ),
    ]
