# Generated by Django 3.1.6 on 2021-05-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0039_auto_20210517_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='refused_to_sign',
            field=models.BooleanField(default=False),
        ),
    ]
