# Generated by Django 3.1.11 on 2021-05-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_auto_20210524_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='message_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
