# Generated by Django 3.1.11 on 2021-05-27 03:31

from django.db import migrations, models
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_auto_20210526_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safetypoint',
            old_name='uploaded',
            new_name='is_signed',
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='edited_by',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='edited_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='employee_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='message_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='refused_to_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='signature_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='status_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetypoint',
            name='witness_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='document',
            field=models.FileField(null=True, upload_to='attendance_forms', validators=[employees.validators.pdf_extension]),
        ),
        migrations.AlterField(
            model_name='safetypoint',
            name='document',
            field=models.FileField(null=True, upload_to='safety_point_forms', validators=[employees.validators.pdf_extension]),
        ),
        migrations.AlterField(
            model_name='safetypoint',
            name='unsafe_act',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
