# Generated by Django 3.1.11 on 2021-05-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0044_auto_20210527_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetypoint',
            name='initials',
            field=models.TextField(blank=True, default=''),
        ),
    ]
