# Generated by Django 3.1.11 on 2021-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0045_safetypoint_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetypoint',
            name='union_representation',
            field=models.BooleanField(default=False),
        ),
    ]
