# Generated by Django 3.1.11 on 2021-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0046_safetypoint_union_representation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counseling',
            old_name='uploaded',
            new_name='is_signed',
        ),
        migrations.AddField(
            model_name='counseling',
            name='edited_by',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='counseling',
            name='edited_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='employee_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='counseling',
            name='initials',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='counseling',
            name='message_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='counseling',
            name='refused_to_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counseling',
            name='signature_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='counseling',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='status_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='union_representation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counseling',
            name='witness_signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
