# Generated by Django 3.1.11 on 2021-06-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0047_auto_20210602_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
