# Generated by Django 3.1.11 on 2021-06-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0048_attendance_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
