# Generated by Django 3.1.11 on 2021-06-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0049_counseling_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='hold',
            name='removed_by',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
