name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Publish Image
        uses: craftech-io/package-action@v3.1.0
        id: url-GPR 
        with:
          tags: latest
          dockerfile: dms.Dockerfile
          access_token: ${{ secrets.DOKERHUB_TOKEN }}  
